### ISSUE TITLE
need helps for errors

### ISSUE THREAD

**Issue by yi213-robotic** [crigroup/openrave-installation#32]
To whom may concern,
   
./install-openrave.sh

Downgrading sympy to version 0.7.1...

WARNING: Ignoring invalid distribution -cipy (/home/yw/Downloads/yes/lib/python3.9/site-packages)
Collecting sympy==0.7.1
  Using cached sympy-0.7.1.tar.gz (3.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-gtvqi1k5/sympy_4040cc95656e411a9867d8ee0a370559/setup.py", line 38
          print "Sympy requires Python 2.5 or newer. Python %d.%d detected" % \
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Sympy requires Python 2.5 or newer. Python %d.%d detected" % \)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Installing OpenRAVE 0.53.1 from source (Commit 2024b03554c8dd0e82ec1c48ae1eb6ed37d0aa6e)...

Cloning into 'openrave'...
remote: Enumerating objects: 95215, done.
remote: Counting objects: 100% (5426/5426), done.
remote: Compressing objects: 100% (1471/1471), done.
^Cceiving objects:  13% (12826/95215), 7.42 MiB | 14.80 MiB/s

Could you please help me fix this errors? BTW, I already reinstall and update sympy. Any help would be appreciate.

**Comment by yurirocha15** [comment]
You're probably installing it using Python 3. As far as I know, the scripts in this repo install everything using Python 2.7.
